### ISSUE TITLE
Rename crate

### ISSUE THREAD

**Issue by xoac** [xoac/endian-serde#1]
I am not quite sure name of this crate is correct. The same suggest it works with serde but it doesn't. 

It transform rust types as little or big endiannes.

Any suggestions are welcome.

**Comment by chrysn** [comment]
packed-endian-struct, maybe (given that the serialization it produces doesn't have padding AFAICT)?

**Comment by xoac** [comment]
I would propose `endian_codec` and I decide to use `_` after reading this [issue](https://github.com/rust-lang/cargo/issues/2775) 

This will also change `SerializeLittleEndain` trait to `EncodeLE`etc.  because the name was to long in practical use.

**Comment by Kixunil** [comment]
How about `binary_codec`?

**Comment by wucke13** [comment]
Quite nice, that name! I suppose that both of you have a look of [packed_struct](https://docs.rs/packed_struct/0.3.0/packed_struct/). It looks like it is unmaintained, and the ergonomics are not super good (e.g. I wasn't able to get started in 20 minutes), however, feature wise it looks really complete & good.

**Comment by xoac** [comment]
Renaming create is still an option. But:
- it has to be much better name (not just better)
- crate has to be fully implemented

I think that the name is lacking of `pack` word so it could be `pack_(with)_endian` or `struct_pack_endian`, `endian_packed` `packed_struct`. I think `pack` should replace `codec` since it can pack and unpack objects what is a special case of codec. 

I would at this moment vote against change the name. Why?:
- the crate is not supper important 
- it's already published to crates.io
- crate can be found by adding category and keywords 
at this moment there are still free slots (and `endian` can be removed - it's in name)
  ```
    keywords = ["no_std", "endian", "bytes"]
    categories = ["no-std", "parsing"]
  ```
- This crate will be probably useful with no_std environment so I added it to [awesome-emebedded-rust](https://github.com/rust-embedded/awesome-embedded-rust/pull/246) to be easier findable 

I will not go with `binary_codec` - because can codec be done without binary? 

I still think that `endian` is good part in name: Look at documentation:
![image](https://user-images.githubusercontent.com/1863020/78679005-f87ee400-78e9-11ea-837b-e77236b108e7.png)
just PackedSize don't contains **endain** in name. At it's just helping trait that I would be happy to hide from the end user.

**Comment by Kixunil** [comment]
I definitely agree with not jumping on renaming too soon! I meant it more as a suggestion if the situation changes.
