### ISSUE TITLE
Add packed_struct to list of similar crates

### ISSUE THREAD

**Issue by wucke13** [xoac/endian-serde#6]
As far as I understand this crate does not only deal with endianess but also with packing and unpacking structs. To me it looks like Rust has quite a weak spot in this domain, because there is really not one widely used/well maintained crate for (de)serializing structs to a custom byte format. Having one more mentioned in your list will hopefully spare some time for someone in the future. 

https://crates.io/crates/packed_struct

**Comment by xoac** [comment]
I will not call packing struct as raw bytes "serializing". This is why I called it  encode / decode (codec).

At this moment this crate will allow you to easy pack struct as bytes (with chosen endianess). System padding is ignored when using derive. 

Feel free to add packed_struct to the list with PR.

**Comment by wucke13** [comment]
> I will not call packing struct as raw bytes "serializing"

Is there reason to that? The definition at [wikipedia](https://en.wikipedia.org/wiki/Serialization) seems to be pretty much like what this library does - I'm interested in your rational to strictly oppose this term for this context.

> Feel free to add packed_struct to the list with PR.

I'll do, thanks for the heads up :)

**Comment by xoac** [comment]
For me:
> In computing, serialization (or serialisation) is the process of translating data structures or object state into a format **that can be stored** (for example, in a file or memory buffer) or transmitted (for example, across a network connection link) and **reconstructed later** (possibly in a different computer environment).

How would you store
```rust
enum MyEnum {
  One(u8),
  Two(u8),
}
```
with my crate? 

In case of this crate both ends of communication need additional knowledge that can't be stored with format.

**Comment by wucke13** [comment]
Well, this is a convincing argument, thanks for the insight
